name: Inspections

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4', '8.5']
    name: PHP ${{ matrix.php-versions }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
      - name: Install dependencies # Verify that the package can be installed for current environment
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Symfony 6.x
        run: |
          composer update --with symfony/console:^6.0 --with symfony/finder:^6.0 -W
          ./vendor/bin/phpunit
          ./vendor/bin/psalm
          ./vendor/bin/phpcs
      - name: Symfony 7.x
        run: |
          composer update --with symfony/console:^7.0 --with symfony/finder:^7.0 -W
          ./vendor/bin/phpunit
          ./vendor/bin/psalm
          ./vendor/bin/phpcs
      - name: Symfony 8.x
        run: |
          composer update --with symfony/console:^8.0 --with symfony/finder:^8.0 -W
          ./vendor/bin/phpunit
          ./vendor/bin/psalm
          ./vendor/bin/phpcs
        if: contains(matrix.php-versions, '8.4') || contains(matrix.php-versions, '8.5')
