name: Inspections

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        symfony-versions: ['^6.0', '^7.0']
    name: PHP ${{ matrix.php-versions }} with Symfony ${{ matrix.symfony-versions }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
      - name: Install dependencies # Verify that the package can be installed for current environment
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Configure Symfony    # Specify desired Symfony version
        run: composer update --with symfony/console:${{ matrix.symfony-versions }} --with symfony/finder:${{ matrix.symfony-versions }} --ignore-platform-reqs -W
      - name: Unit tests
        run: ./vendor/bin/phpunit
      - name: Static Analysis
        run: ./vendor/bin/psalm
      - name: Code style
        run: ./vendor/bin/phpcs
